### ISSUE TITLE
Allow piping of current line

### ISSUE THREAD

**Issue by Iss-in** [raitonoberu/sptlrx#1]
Hi, first off a great thanks for creating something like this , its really an awesome feature , been looking for something like this since forever. 

- will it be possible to pipe out the output so any other application can use it as well. A great application of it will be to be able to show the current lyric line in waybar/polybar  

- also will it be possible to have a offset for lyrics ( can be both ve/+ve )

**Comment by raitonoberu** [comment]
Hello @Iss-in!
Next release will allow piping. You will be able to use it in polybar like this:
```
[module/sptlrx]
type = custom/script
exec = sptlrx pipe
tail = true
```
My goal is to make it scrollable. `zscroll` doesn't have the option to scroll "tail" scripts, so I'll either make a PR or write my own scrolling mechanism, with blackjack and Go :). But this is postponed until the next release.

Peace.

**Comment by Iss-in** [comment]
thanks, this worked as expected. Awesome :)
