### ISSUE TITLE
Lyrics won't work for Mopidy-Spotify

### ISSUE THREAD

**Issue by websitefortilde** [raitonoberu/sptlrx#11]
I tried it with the spotify app and it worked perfectly. But for some reason it won't work with mopidy-spotify. Is there any way to make it work?

**Comment by raitonoberu** [comment]
Unfortunately, this won't work until mopidy-spotify supports Spotify Connect (https://github.com/mopidy/mopidy-spotify/issues/14). `ncspot` doesn't work for the same reason.

But it should be possible to add MPD support using its API — will be tracked in #12.
