### ISSUE TITLE
[FEATURE] TimeStamp and Export stdout

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [raitonoberu/sptlrx#14]
Hey, should be a simple idea, but to be able to include the timestamp in the stdout and also a --export to just download the entire .lrc file. since, there's not a single working/reliable .lrc downloader

**Comment by raitonoberu** [comment]
Closed, see [#22](https://github.com/raitonoberu/sptlrx/pull/22#issuecomment-1380747847) for details.
