### ISSUE TITLE
Clear lyrics when Spotify client is closed

### ISSUE THREAD

**Issue by Kuuhhl** [raitonoberu/sptlrx#20]
When I close my spotify client, sptlrx continues to go through the lyrics until it gets to the end of the song. Would it be possible to clear the output when the spotify client is no longer running?
I am using `sptlrx pipe` in polybar and it continues to update the lyrics for minutes after I closed Spotify.

**Comment by raitonoberu** [comment]
The problem is that Spotify tracks progress on its servers and returns it to all clients (that's how Spotify Connect works). It doesn't know you've closed the client, at least not right away. There's nothing we can do about it.
