### ISSUE TITLE
Option to hide errors

### ISSUE THREAD

**Issue by Kuuhhl** [raitonoberu/sptlrx#21]
When using a device without a constant internet connection (e.g. laptop), the script shows an Error, as it can't access the spotify api (`Error: Get "https://open.spotify.com/get_access_token?reason=transport&productType=web_player"`...).
This error message shows up on my status bar, when I would rather have it not show anything if it can't access the internet.
Could you add an option/flag to hide it?

**Comment by raitonoberu** [comment]
Fixed in [v1.1.0](https://github.com/raitonoberu/sptlrx/releases/tag/v1.1.0). Errors are now ignored by default, this can be overridden in `config.yaml` or by passing the `--verbose` flag.
