### ISSUE TITLE
How install in raspberry pi?

### ISSUE THREAD

**Issue by 9acca9** [raitonoberu/sptlrx#24]
Hi.
I try the 

curl -sSL instl.sh/raitonoberu/sptlrx/linux | bash  

This happened:

` i Found latest release of sptlrx (version: v1.0.0)
 i Found 9 assets in 'v1.0.0' release - searching for one that fits your system...
 i Found asset with highest match score: sptlrx_1.0.0_linux_arm64.tar.gz
 i Downloading asset...
 i Installing 'sptlrx'
 i Running clean up...
`

But, im using raspberry pi 2, that is a 32bit. 

what can i do?
Thanks.

**Comment by 9acca9** [comment]
oh, i see the documentation for build it! Thanks for your work.

But, i want to ask, if... im using mopidy, and i will like to see the synchronized lyrics in the web browser... it will be too complicated to do? in that way we can sign along with partners. My family and i like to sign together, so... we can access that local web and look the lyrics.

i mean a local web just like the terminal, nothing fancy.

**Comment by raitonoberu** [comment]
Hi @9acca9! I got your email. Sorry for the delay, I've spent the last few days on the train coming home 😅

As for the initial problem, thank you for reporting it. The next release will contain ARMv6 binaries.

---

sptlrx supports displaying song lyrics only in the terminal. If there is a way to display your terminal in the browser, you can use it to view the lyrics in the browser, but to be honest, I don't think it's possible.

By the way, why are you looking for a web client? You can run Mopidy on your Raspberry Pi, allow access from the local network (more details [here](https://docs.mopidy.com/en/latest/ext/http/)) and run sptlrx on another PC (replace the local address with the IP of your RPI in the [config](https://github.com/raitonoberu/sptlrx#mopidy)).

Also, I'm not sure if this will fit your needs, but I'm currently working on a fancy desktop application for showing lyrics, and it will support all the players that sptlrx supports. It is in an early stage of development and I will make the repository publicly available as soon as I am sure it is stable.
<details>

![Screenshot](https://user-images.githubusercontent.com/64320078/214096373-49e16fd5-c025-4fa2-9354-1894e086daef.png)
</details>

**Comment by 9acca9** [comment]
Thanks for the answer!
It will be better for us (family, friends) because will all have android phones to connect to a local web (i think). More easy, i mean. 
I have mopidy in the raspberry pi with a DAC (iqaudio pro) to play from Qobuz (qobuz dont show lyrics...).
Anyway, i did not know (what a fool...) that i can connect remote! that is really good! (im gonna take a notebook and connect from there to the mopidy server!).

Good that you are developing the desktop app for show the lyrics also (if you make it for android also.... lol (always asking), it will be pretty good (even if you can't put it on the play store, at least for the users (lol)) (this is why i think that a web version is good because you can run that in every place)

Anyway, thanks for your work and for taking the time to answer!

> I've spent the last few days on the train coming home sweat_smile
the trans-siberian train?

**Comment by raitonoberu** [comment]
[v1.1.0](https://github.com/raitonoberu/sptlrx/releases/tag/v1.1.0l) contains **armv6** binaries. The web version will be tracked in #26.
