### ISSUE TITLE
[Feature Request] Font size change

### ISSUE THREAD

**Issue by TWB0109** [raitonoberu/sptlrx#25]
The vim plugin zen-mode by folke has the ability to change the font size of Kitty, Wezterm and Alacritty. 

[Here's an example](https://github.com/folke/zen-mode.nvim/blob/6e6c963d70a8e47854fa656987666bfb863f9c4e/lua/zen-mode/plugins.lua) in lines 36-75. I would do it myself, but I'm not knowledgeable enough in  Go or in programming in general.

This would allow for the lyrics window to have a different font size making it more readable, this can be done easily by zooming in, but adjusting the font size this way means that it can then be reversed after the application closes.

This is just an idea and I would understand it if it's not implemented

**Comment by raitonoberu** [comment]
I don't like the idea of writing "terminal emulator specific" code... There's probably a better way to implement it. Maybe a bash script that would set the desired font size, open `sptlrx` and wait for it to close, then return it to normal?
