### ISSUE TITLE
Any plans to support FreeBSD?

### ISSUE THREAD

**Issue by duckyondiscord** [raitonoberu/sptlrx#32]
(Or *BSD if that's easily doable)
Currently it doesn't build on FreeBSD because the mpris source files are only for Linux, Windows, and Darwin.
I was wondering if there were any plans to support BSDs in there, in theory they should be similar or even the same as Linux.

**Comment by raitonoberu** [comment]
Hello, @duckyondiscord. I don't know anything about FreeBSD, but after a quick googling I found out that it also uses D-Bus ([source](https://forums.freebsd.org/threads/why-do-we-need-d-bus.78868/)). So the same implementation as in Linux should work here as well. You should be able to compile it by simply renaming `mpris_linux.go` to `mpris_freebsd.go`. As for providing the "official" binaries, first of all I want confirmation that this actually works :)

**Comment by duckyondiscord** [comment]
> Hello, @duckyondiscord. I don't know anything about FreeBSD, but after a quick googling I found out that it also uses D-Bus ([source](https://forums.freebsd.org/threads/why-do-we-need-d-bus.78868/)). So the same implementation as in Linux should work here as well. You should be able to compile it by simply renaming `mpris_linux.go` to `mpris_freebsd.go`. As for providing the "official" binaries, first of all I want confirmation that this actually works :)

Sure thing, I'll try and report back!

**Comment by duckyondiscord** [comment]
![image](https://github.com/raitonoberu/sptlrx/assets/94759537/402f8a48-a6f3-4294-8589-cfc6e1f09c1a)
@raitonoberu I am pleased to say that it just works, so you just need to make a copy of mpris_linux.go and name it mpris_freebsd.go :D

**Comment by duckyondiscord** [comment]
Other BSDs will probably also work but that still needs testing :p

**Comment by duckyondiscord** [comment]
On second thought I'll reopen this until it gets implemented as to not confuse people
