### ISSUE TITLE
Eye candies on lyrics displaying

### ISSUE THREAD

**Issue by aik2mlj** [raitonoberu/sptlrx#4]
Thanks for this great terminal app! I'd like to nitpick a bit regarding to the way the lyrics are displayed.
- Currently the lines that have been played are also highlighted. I think it's more appealing to have only the current line highlighted with other lines (played and yet to be played) dimmed. If you are not interested, providing an option to change this behavior is greatly appreciated!
- Is it possible to make the font size of the current line a bit bigger? It would be more immersive that way in my opinion.

Love!

**Comment by raitonoberu** [comment]
Hello @aik2mlj! Thank you for your kind words, I am sincerely glad that you liked the app.

I am currently refactoring the code to use a powerful CLI framework ([dev](https://github.com/raitonoberu/sptlrx/tree/dev) branch). This way it will be easy to add customization options. I was planning to add only a color change option, but you gave me a great idea.

It is not possible to change the font size of a single character/line in the terminal. All symbols have the same width and height. We can only change the color or make it bold to increase the contrast.

Next release will contain a lot of customization! Hopefully I'll find some time to finish it (exams are coming up)...

**Comment by aik2mlj** [comment]
Glad to hear that! Hope you're doing great with your exams. ;P

**Comment by raitonoberu** [comment]
`v0.2.0` allows you to customize the appearance of the lines.
> I think it's more appealing to have only the current line highlighted with other lines dimmed.

This can be done with `sptlrx --before faint`:
<details>

![image](https://user-images.githubusercontent.com/64320078/155846580-7be7bb3c-b4a9-4bbe-bebf-e85ea8ad06a5.png)
</details>

More options in the README. If you run `sptlrx` manually, you can create an alias in your shell. I will probably add the ability to create a config file in the next release.

Peace.
