### ISSUE TITLE
Bug: Typo in Config File

### ISSUE THREAD

**Issue by ethangillengg** [raitonoberu/sptlrx#41]
First of all I just wanted to say wow, this project is awesome!! I have been looking for a lyrics player in the terminal for a while now so this is great, thanks for your hard work 😄

## Bug Description
I noticed there is a typo in the config file, and README.md where it says `undeline` instead of `underline`. The config seems to only work when you use the typo. The CLI args it work as expected, it is just in the `config.yaml` file.

Thanks!

## Platform
NixOS 24.05 (Uakari)
## Version
sptlrx version v1.1.0

**Comment by raitonoberu** [comment]
Thank you for reporting! What a stupid typo, and it looks like it's been here for a long time 😅
Fortunately, I'm pretty sure that no one uses this option anyway, so it's quite safe to fix it.
