### ISSUE TITLE
Enjoy lyrics on Spotify Premium.

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/sptlrx#46]
<img src="https://github.com/raitonoberu/sptlrx/assets/64320078/c00f0dba-957a-4889-a9e0-c0f389b99478" width="500"></img>

Greedy fuckers.

**Comment by raitonoberu** [comment]
https://community.spotify.com/t5/Your-Library/Lyrics-are-missing-for-free-users/td-p/5631421/page/5

**Comment by duckyondiscord** [comment]
Oh so THAT's why sptlrx stopped working, well, best of luck sorting it out. Corpos are getting unpredictably greedy...

**Comment by 9acca9** [comment]
it seems 3 the best.

**Comment by raitonoberu** [comment]
Sorry guys, I will definitely make it work again, but I can't give you any time estimates as I have hardly any free time these days.

I would really appreciate it if someone could submit a PR to [lyricsapi](https://github.com/raitonoberu/lyricsapi) with lrclib.net support.

**Comment by raitonoberu** [comment]
Closed in favor of #48

**Comment by BEST8OY** [comment]
@raitonoberu 
Just a notice
I'm not sure how long has it been but I just noticed I have the full lyrics back for free!
