### ISSUE TITLE
Offset by a few milisecond late

### ISSUE THREAD

**Issue by barraIhsan** [raitonoberu/sptlrx#50]
As you can see the video here (audio on)

https://github.com/raitonoberu/sptlrx/assets/57800056/1897a66b-b35d-4c57-9205-ab0db95b4185

(on the left, I have mpv opened with the lrc file loaded, and on the right is ncmpcpp (mpd) + sptlrx)

I know it's not *that big of a difference*, but it would be nice to add "offset" in the config.

**Comment by raitonoberu** [comment]
It's relatively easy to add this field, but I'm afraid it won't improve the situation. We don't add the delay intentionally, it arises from the player reporting incorrect position and/or poorly mapped lyrics (but I see that your lyrics are fine). So the value you set as the “offset” depends on many factors, and while it may eliminate delay in some cases, it will add it in others.
