### ISSUE TITLE
ui enhancmet

### ISSUE THREAD

**Issue by shin01221** [raitonoberu/sptlrx#54]
can you please add a way to control font size or if there's a way can someone please help

**Comment by raitonoberu** [comment]
my brother in Christ, it's completely up to your terminal emulator. try `ctrl` and `+` or `ctrl` and scrolling your mouse wheel.
if it doesn't help, try to google "how to change font size in konsole/alacritty/gnome-terminal/whatever-you-are-using". good luck and have a nice day.

**Comment by shin01221** [comment]
i'm using kitty and i fixed this i think the problem was me using the value 9.5 it needed to higher value on this window 
thanks for help and this amazing tool
