### ISSUE TITLE
Is it possible to authenticate using spotify api instead of cookie

### ISSUE THREAD

**Issue by edgerunning** [raitonoberu/sptlrx#56]
Is it possible to connect using the spotify api, like [spotify-tui](https://github.com/Rigellute/spotify-tui#connecting-to-spotifys-api) does. I am not sure if keeping cookie in a config file is a good idea.

**Comment by raitonoberu** [comment]
Sorry, no. Lyrics API is reverse-engineered, they don't allow public usage of it. As for your problem, there are other ways to specify cookie.

> You can also set the SPOTIFY_COOKIE enviroment variable or pass the --cookie flag.

**Comment by edgerunning** [comment]
I see. But a similar project [lyricstify](https://github.com/lyricstify/lyricstify#initializing-configuration) uses this method to authenticate without having to retrieve the cookie yourself, so I thought it might be possible.
