### ISSUE TITLE
Couldn't create client: invalid cookie provided

### ISSUE THREAD

**Issue by Gcat101** [raitonoberu/sptlrx#6]
I copied my cookie exactly like the instruction said and I got:
`Couldn't create client: invalid cookie provided`

**Comment by raitonoberu** [comment]
Hello @Gcat101!
Please make sure that your cookie looks like this: `sp_t=dc958f46698dbf32e7f5b0b84b3o5fce; sp_dc=AQD3W6rxgiHyaqFVY6qheH3nXzAzRWwHKvMPtPYdkRK9Z4A; sp_key=f6924e76-3345-23f6-a7c5-54sd230f11c3; <other fields>`. It should contain these 3 fields: `sp_t`, `sp_dc` and `sp_key`. You probably copied the wrong field. If not, I have no idea😕

**Comment by Gcat101** [comment]
there are no sp_dc and sp_key fields

**Comment by raitonoberu** [comment]
These fields may be missing if you are not logged into the Spotify web client.

Or you may be copying the wrong field. There is one called `set-cookie` - not what we want:
<details>

![image](https://user-images.githubusercontent.com/64320078/155489695-1cae2393-dc6f-4573-9c63-09ba3533a2f3.png)
</details>

If so, scroll down to the `Request Headers` and copy the `cookie` field.
<details>

![image](https://user-images.githubusercontent.com/64320078/155489773-78791d8d-28fe-4221-818e-057d0eb05613.png)
</details>

I know the setup is a bit complicated, but there is no other way. Hope this helps.

**Comment by Gcat101** [comment]
It turns out I wasn't logged in. Sorry!
